# Generated by Django 4.2.5 on 2023-09-06 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.TextField(max_length=50)),
                ('last_name', models.TextField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=200)),
                ('password', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('car_model_id', models.AutoField(primary_key=True, serialize=False)),
                ('make', models.CharField(blank=True, max_length=50)),
                ('model', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('street_name', models.CharField(max_length=100)),
                ('street_number', models.BigIntegerField()),
                ('zip_code', models.BigIntegerField()),
                ('city', models.CharField(max_length=50)),
                ('acc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appU', to='cars_db.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.AutoField(primary_key=True, serialize=False)),
                ('number_of_owners', models.IntegerField()),
                ('registration_number', models.CharField(max_length=30)),
                ('manufacture_year', models.BigIntegerField()),
                ('number_of_doors', models.IntegerField()),
                ('mileage', models.BigIntegerField()),
                ('car_mod_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car', to='cars_db.carmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('advertisement_id', models.AutoField(primary_key=True, serialize=False)),
                ('advertisement_date', models.DateField(auto_now=True)),
                ('car_identification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carid', to='cars_db.car')),
                ('seller_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app', to='cars_db.appuser')),
            ],
        ),
    ]
